"""initial schema

Revision ID: 0deac46d0e66
Revises: 
Create Date: 2026-08-30 14:04:48.762425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('session_year', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('has_practical', sa.Boolean(), nullable=False),
    sa.Column('theory_full', sa.Integer(), nullable=False),
    sa.Column('theory_pass', sa.Integer(), nullable=False),
    sa.Column('practical_full', sa.Integer(), nullable=False),
    sa.Column('practical_pass', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('theory_obtained', sa.Float(), nullable=True),
    sa.Column('practical_obtained', sa.Float(), nullable=True),
    sa.Column('theory_absent', sa.Boolean(), nullable=False),
    sa.Column('practical_absent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', name='uq_mark')
    )
    op.create_table('student_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('gpa_without_optional', sa.Float(), nullable=False),
    sa.Column('optional_bonus', sa.Float(), nullable=False),
    sa.Column('compulsory_average_mark', sa.Float(), nullable=False),
    sa.Column('flags', sa.String(length=300), nullable=False),
    sa.Column('failing_subjects', sa.String(length=300), nullable=False),
    sa.Column('trace_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_results')
    op.drop_table('marks')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
